[package]
name = "example-simple"
version = "0.1.0"
authors = []
edition = "2018"
publish = false

[dependencies]
env_logger = "0.7"
gdk = "0.13.2"
gio = "0.9.1"
glib = "0.10.0"
gtk = "0.9.0"
log = "0.4.11"
rt-graph = { path = "../.." }