[package]
name = "example-gtk"
version = "0.1.0"
authors = []
edition = "2018"
publish = false

[dependencies]
env_logger = "0.7"
gio = "0.9.1"
gtk = "0.9.0"
log = "0.4.11"
rt-graph = { path = "../.." }